### ISSUE TITLE
Using Windows Auth

### ISSUE THREAD

**Issue by 274188A** [KevinDockx/SecuringBlazorClientSideApplications#3]
There's a problem i saw when navigating from add new employee back to overview.

If you log in as a new user (i used win auth) then go to add a new employee, but then instead click the "back to overview" button - you get trapped in the 'logging you in" screen.

I suspect the button 'back to overview' should not be visible to the user i was logged in as?

**Comment by KevinDockx** [comment]
Just had a look - the reason for this is that the new user won't have a country claim, which means (s)he is not authorized to access the employeeoverview page due to the CanManageEmployees policy.  You could write a bit of code that would navigate away if the user isn't authorized or any other custom rule you might want to implement.  For that, you can use the RedirectToLogin razor page.  

In a real-life situation you would probably also require the new user to input a country claim when registering.  That's a bit out of scope for this course, but I cover that in this course: https://app.pluralsight.com/library/courses/dealing-credentials-when-securing-aspdotnet-core-3-application/table-of-contents  

Hope this helps :)
